---
# Secures server and install main software

- name: Update APT package cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: Install unattended-upgrades
  apt: pkg=unattended-upgrades state=present

- name: Adjust APT update intervals
  copy: src=apt_periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Make sure unattended-upgrades only installs from $ubuntu_release-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-dates" state=absent

- name: Disable SSH strict host key checking to allow git to clone unattended
  copy: src=ssh_config dest=/home/deploy/.ssh/config

- name: Install required software packages
  apt: pkg={{ item }} state=installed
  with_items:
  - git-core
  - build-essential
  - python-software-properties
  - g++
  - make
  - htop
  - iftop
  - iotop
  - vim-nox
  - subversion
  - mercurial
  - bzr
  - python-pycurl
  - golang

- name: Update APT package cache
  apt: update_cache=yes

#- include: swap.yml tags=swap
