---
# Deploys the crawler application

- name: Ensure crawler directory exists
  file: dest=/home/gostats/crawler owner=gostats group=gostats state=directory

- name: Copy package to sever and unpack it
  unarchive: src=../../../../build/tgz/crawler.tar.gz dest=/home/gostats

- name: Cleaning up
  file: dest=/tmp/crawler.tar.gz state=absent

- name: Set permissions
  file: path=/home/gostats/crawler/crawler group=gostats owner=gostats mode=0754

- name: Ensure cron job exists
  cron: name="gostats crawler" hour=6 minute=0
        user="gostats" job="cd /home/gostats/crawler && ./crawler -out data >> /var/log/gostats/crawler.log 2>&1"

- name: Ensure cron job for cleaning up the data directory
  cron: name=:"gostats clean data directory" hour=0 minute=0
        user="gostats" job="find /home/gostats/crawler/data/* -mtime +30 -exec rm {} \;"
