---
# Deploys the crawler

- name: Ensure build directory exists
  file: dest=/home/gostats/build owner=gostats group=gostats state=directory

- name: Ensure required GOPATH directories exist
  file: dest={{ item.dest }} owner=gostats group=gostats state=directory
  with_items:
  - { dest: '/home/gostats/build/src/github.com/hypebeast' }
  - { dest: '/home/gostats/build/pkg' }
  - { dest: '/home/gostats/build/bin' }

- name: Synchronize crawler files
  synchronize: src=../../../../../gostats dest=/home/gostats/build/src/github.com/hypebeast group=no owner=no rsync_opts=--exclude=.git,--exclude=deployment,--exclude=web

- name: Install all dependencies
  command: go get github.com/PuerkitoBio/goquery
  args:
    chdir: /home/gostats/build
  environment:
    GOPATH: /home/gostats/build

- name: Build crawler
  command: go build crawler.go
  args:
    chdir: /home/gostats/build/src/github.com/hypebeast/gostats/crawler
  environment:
    GOPATH: /home/gostats/build

- name: Ensure crawler directory exists
  file: dest=/home/gostats/crawler owner=gostats group=gostats state=directory

- name: Copy crawler executable
  command: cp /home/gostats/build/src/github.com/hypebeast/gostats/crawler/crawler /home/gostats/crawler

- name: Remove build directory
  file: dest=/home/gostats/build state=absent

- name: Ensure cron job exists
  cron: name="gostats crawler" hour=6 minute=0
        user="gostats" job="cd /home/gostats/crawler && ./crawler -out data >> /var/log/gostats/crawler.log 2>&1"

- name: Ensure cron job for cleaning up the data directory
  cron: name=:"gostats clean data directory" hour=0 minute=0
        user="gostats" job="find /home/gostats/crawler/data/* -mtime +30 -exec rm {} \;"
