---
# Deploys the Google BigQuery sync script

#- name: Copy crontab file
#  copy: src=bigquery.cron dest=/etc/cron.d

- name: Ensure sync script directory exists
  file: dest=/home/gostats/bigquery owner=gostats group=gostats state=directory

- name: Copy package to sever and unpack it
  unarchive: src=../../../../build/tgz/bigquery.tar.gz dest=/home/gostats

- name: Cleaning up
  file: dest=/tmp/crawler.tar.gz state=absent

- name: Set permissions
  file: path=/home/gostats/bigquery/sync.sh group=gostats owner=gostats mode=0754

- name: Copy schema files
  copy: src={{ item }} dest=/home/gostats/bigquery group=gostats owner=gostats
  with_items:
  - github_schema.json 
  - godoc_schema.json 

- name: Ensure cron job exists
  cron: name="gostats sync with bigquery" hour=0 minute=15
        user="gostats" job="/home/gostats/bigquery/sync.sh -d /home/gostats/crawler/data >> /var/log/gostats/sync.log 2>&1"

